### PR TITLE
Improve README landing page

### PR DESCRIPTION
**Pull request by dragonhunt02**

### CODE REVIEW

**Comment by fire** [comment]
you might want to rebase, the readme doesn’t match master anymore

**Comment by dragonhunt02** [comment]
I should remove Contributors section?

**Comment by fire** [comment]
Do you know how to squash?

**Comment by dragonhunt02** [comment]
I apologize, I forgot it

**Comment by dragonhunt02** [comment]
Apologies, I forgot it

**Comment by fire** [comment]
Can you rebase? the image failed to load.

**Comment by fire** [comment]
Thanks for contributing. I have made your changes.

**Pull request closed without merging**
